### ISSUE TITLE
Enabling during installation process doesn't work

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/simplenews_content_selection#3]
As [described here](https://github.com/backdrop-ops/contrib/issues/698#issuecomment-1398978201) it's not possible to enable the module during installation process. But it is possible to enable it manually via /admin/modules/list.

**Comment by argiepiano** [comment]
Thanks for reporting. I believe this is because of the way Backdrop handles modules - it expects the git repository to have the same name as the module files. In this case (because of the way it was done in Drupal), the git repository is called `simplenews_content_selection`, but the module files are `scs`. 

This is problematic. I'll basically need to re-release this with a different name. Meaning that people will need to complete uninstall the module, remove it manually from the `modules` folder, and reinstall....  Good thing we are still in `alpha`!

**Comment by argiepiano** [comment]
@djzwerg I will do a new release that fixes this. It's REALLY important that you follow these steps. 

1. Disable Simplenews Content Selection
2. REMOVE its folder from the modules folder
3. Do a completely new installation of the module from the latest version that will be released later tonight (1.x-2.0.1)

Let me know if you encounter any issues.
