### ISSUE TITLE
Bug (1.x-2.0.1-beta): No possibility to choose the content

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/simplenews_content_selection#8]
As you can see here I'm not able to check which node should be presented within the newsletter:

![grafik](https://user-images.githubusercontent.com/49948628/215226004-d7474d44-a00d-45cb-ad93-56e0ff46bb92.png)

**Comment by djzwerg** [comment]
To solve this I had to edit the view and select Views Bulk Operations: Create newsletter.

But I think this should be done during installation process, doesn't it?

**Comment by argiepiano** [comment]
@djzwerg this happened because you uninstalled the old (faulty) version. When you uninstalled, the View was still present in your site. When you installed the new version, the new View was not installed because it already existed. 

If you try doing a "clean" install in a site that did not have the old version, you will not have this problem. 

Closing, since this is just a special issue that happened only because of the change in the base name of the module.

**Comment by djzwerg** [comment]
@argiepiano I've uninstalled the old version and deleted it from the file system before. The cache was also cleared.

**Comment by argiepiano** [comment]
I understand, but the View doesn't get removed when you uninstall the module, even if you clear the cache. This is the standard behavior of installed Views.

**Comment by djzwerg** [comment]
@argiepiano sorry for the delay. Works as designed.
